### ISSUE TITLE
运行步骤1

### ISSUE THREAD

**Issue by HUANGSHENGBO** [justwiner/microfront-end-single-spa#1]
运行步骤1如何开启服务?
是新建一个http-server就可以吗?

**Comment by justwiner** [comment]
嗯，主要目的是在公共依赖文件夹下，开启一个HTTP服务，可以通过http请求加载公共依赖，如果你有其他cdn连接也是可以加载的。
源码在此：https://github.com/justwiner/microfront-end-single-spa/blob/master/portal/src/common-deps.js
所有的公共依赖都是通过http请求加载的

**Comment by HUANGSHENGBO** [comment]
非常感谢


------------------ 原始邮件 ------------------
发件人: justwiner <notifications@github.com&gt;
发送时间: 2019年8月29日 18:47
收件人: justwiner/microfront-end-single-spa <microfront-end-single-spa@noreply.github.com&gt;
抄送: HUANGSHENGBO <1092864705@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[justwiner/microfront-end-single-spa] 运行步骤1 (#1)




嗯，主要目的是在公共依赖文件夹下，开启一个HTTP服务，可以通过http请求加载公共依赖，如果你有其他cdn连接也是可以加载的。
 源码在此：https://github.com/justwiner/microfront-end-single-spa/blob/master/portal/src/common-deps.js
 所有的公共依赖都是通过http请求加载的
