### ISSUE TITLE
hs -p 8000 --cors

### ISSUE THREAD

**Issue by MacleZhou** [justwiner/microfront-end-single-spa#15]
run.bat中最后一个start cmd /k "cd portal/common-deps-static&&hs -p 8000 --cors"中的hs是啥命令，我的报错

D:\WebSpace\microfront-end-single-spa\portal\common-deps-static>hs -p 8000 --cors
'hs' is not recognized as an internal or external command,
operable program or batch file.

要安装啥？

**Comment by justwiner** [comment]
这个是`http-server插件命令的缩写`，需要全局安装`http-server`插件

**Comment by MacleZhou** [comment]
Thank you
