### ISSUE TITLE
运行 project2项目 报了个错 

### ISSUE THREAD

**Issue by zhaoxm469** [justwiner/microfront-end-single-spa#2]
在浏览器 访问 http://localhost:8237/
打不开页面 
控制台报了个错误 
![image](https://user-images.githubusercontent.com/26950016/65416759-23f92000-de2b-11e9-8e7b-a3c4cbf61a42.png)

**Comment by tongyafang** [comment]
解决了吗，我也遇到了这个问题

**Comment by justwiner** [comment]
我本地运行没这个问题呀，不知道你们是怎么运行的

**Comment by panpanYU** [comment]
![image](https://user-images.githubusercontent.com/11899834/72200732-f2fb3480-3487-11ea-8034-d85c4d5db4f8.png)
这个问题咋回事啊？

**Comment by justwiner** [comment]
这个问题是，启动模式的问题，现在project1、project2、menu项目分别新增了本地开发模式下的启动命令：npm run dev:local，通过这个命令，单独运行各个项目，就可以打开各个项目的页面了

**Comment by liuyaoShuai** [comment]
开启`公共依赖模块的服务`，我的公共依赖模块在portal项目下common-deps-static文件夹中，只需要在这个文件夹下开启服务即可，可以通过http-server插件，端口设置为`8000`，并且设置跨域`

这个要怎么操作呀

**Comment by justwiner** [comment]
> 开启`公共依赖模块的服务`，我的公共依赖模块在portal项目下common-deps-static文件夹中，只需要在这个文件夹下开启服务即可，可以通过http-server插件，端口设置为`8000`，并且设置跨域`
> 
> 这个要怎么操作呀

首先你要确定你有没有启动一个静态服务的工具，没有的话可以安装 http-server，`npm i http-server -g`  
然后你需要在`/portal/common-deps-static/`路径下，执行命令`hs -p 8000 --cors`，即可

**Comment by liuyaoShuai** [comment]
非常感谢 ，好厉害啊

**Comment by justwiner** [comment]
> 非常感谢 ，好厉害啊

感谢支持！
